name: Coupon Codes
main: com.lala.CouponCodes.CouponCodes
version: 1.5
author: 'LaLa'
commands:
    coupon:
        description: Coupon
        usage: |
               /<command> - See forum post for more details on syntax
    c:
        description: Coupon
        usage: |
               /<command> - See forum post for more details on syntax